src/STS.Web/Components/CompanyDocumentsGridViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using STS.Application.Filters;
using STS.Application.Services.Interfaces;

namespace STS.Web.Components
{
    public class CompanyDocumentsGridViewComponent : ViewComponent
    {
        private readonly ICompanyService companyService;

        public CompanyDocumentsGridViewComponent(ICompanyService companyService)
        {
            this.companyService = companyService;
        }

        public IViewComponentResult Invoke(IFilter filter, int companyId)
        {
            var filterResult = companyService.FilterDocuments(filter, companyId);
            return View(filterResult);
        }
    }
}

src/STS.Web/Components/CompanyUsersGridViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using STS.Application.Filters;
using STS.Application.Services.Interfaces;

namespace STS.Web.Components
{
    public class CompanyUsersGridViewComponent : ViewComponent
    {
        private readonly ICompanyService companyService;

        public CompanyUsersGridViewComponent(ICompanyService companyService)
        {
            this.companyService = companyService;
        }

        public IViewComponentResult Invoke(IFilter filter, int companyId)
        {
            var filterResult = companyService.FilterUsers(filter, companyId);
            return View(filterResult);
        }
    }
}

src/STS.Web/Controllers/CompanyController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using STS.Application.Filters;
using STS.Application.Models.Company;
using STS.Application.Models.Document;
using STS.Application.Models.User;
using STS.Application.Services.Interfaces;
using STS.CrossCutting.Enums;
using STS.Web.Components;

namespace STS.Web.Controllers
{
    [Authorize(Roles = nameof(UserRole.CompanyUser))]
    public class CompanyController : BaseController
    {
        private readonly ICompanyService companyService;

        public CompanyController(ICompanyService companyService)
        {
            this.companyService = companyService;
        }

        public IActionResult Index()
        {
            return View();
        }

        #region Documents
        public IActionResult Documents()
        {
            ViewBag.CompanyId = CompanyId;
            return View();
        }

        [ResponseCache(CacheProfileName = "NoChache")]
        public IActionResult GetDocuments(Filter filter)
        {
            return ViewComponent(typeof(CompanyDocumentsGridViewComponent), new { filter, CompanyId });
        }

        public IActionResult AddDocument()
        {
            var viewModel = companyService.GetDocumentUploadViewModel(CompanyId);
            return View(viewModel);
        }

        [HttpPost]
        public JsonResult AddDocument(DocumentUploadModel documentUploadModel)
        {
            var saveResult = companyService.SaveDocumentTemporary(documentUploadModel.DocumentModel);
            if (!ModelState.IsValid || saveResult.Error)
            {
                var fieldNames = ModelState.Keys.ToList();
                var errors = new Dictionary<string, string>();
                foreach (var fieldName in fieldNames)
                {
                    var error = ModelState[fieldName].Errors.FirstOrDefault();
                    if (error != null)
                        errors.Add(fieldName, error.ErrorMessage);
                }
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(errors);
            }
            companyService.SaveDocument(documentUploadModel, UserId);
            return Json(new { message = "Success" });
        }
        #endregion

        #region Users
        public IActionResult Users()
        {
            ViewBag.CompanyId = CompanyId;
            return View();
        }

        [ResponseCache(CacheProfileName = "NoChache")]
        public IActionResult GetUsers(Filter filter)
        {
            return ViewComponent(typeof(CompanyUsersGridViewComponent), new { filter, CompanyId });
        }

        [HttpGet]
        public IActionResult EditUser(int? userId = null)
        {
            var viewModel = companyService.GetUserEditViewModel(userId);
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult EditUser(UserEditViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Check input data");
                return View(viewModel);
            }
            if (viewModel.Id > 0)
            {
                companyService.UpdateUser(viewModel, CompanyId);
            }
            else
            {
                companyService.AddUser(viewModel, CompanyId, UserId);
            }
            return RedirectToAction(nameof(Users));
        }
        #endregion

        #region Metrics
        [HttpGet]
        [ResponseCache(CacheProfileName = "NoChache")]
        public IActionResult Metrics(int? id)
        {
            var model = companyService.GetMetricsViewModel(id ?? 0, CompanyId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Metrics(MetricsViewModel model)
        {
            foreach (var error in companyService.CheckYear(CompanyId, model))
            {
                ModelState.AddModelError(nameof(model.LastDayOfTheYear), error);
            }
            if (!ModelState.IsValid)
            {
                companyService.RestoreMetricsViewModel(model, CompanyId);
                return View(model);
            }
            if (model.Id == 0)
            {
                var metricId = companyService.AddMetric(model, CompanyId);
                return RedirectToAction("Metrics", new { id = metricId });
            }
            if (model.Id > 0 && companyService.GetMetrics(CompanyId).Any(x => x.Id == model.Id))
            {
                companyService.UpdateMetric(model, CompanyId);
                return RedirectToAction("Metrics", new { id = model.Id });
            }
            return RedirectToAction("Metrics");
        }
        #endregion

        public IActionResult Sustainability(int? categoryId = null)
        {
            var hasAccess = companyService.HasAccess(CompanyId, categoryId ?? 0);
            var isCategoryExist = companyService.IsCategoryExist(categoryId ?? 0);
            if (!hasAccess && !isCategoryExist)
            {
                return RedirectToAction("PageNotFound", "Error");
            }
            var targetCategoryId = !hasAccess
                ? companyService.GetActualCategoryId(CompanyId)
                : categoryId ?? companyService.GetActualCategoryId(CompanyId);
            var model = companyService.GetSustainabilityPageViewModel(CompanyId, targetCategoryId);
            return View(model);
        }

        #region Survey

        public IActionResult Survey()
        {
            var viewModel = companyService.GetSurveyViewModel(CompanyId);
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Survey(SurveyViewModel viewModel)
        {
            companyService.SubmitQuestions(viewModel.Questions, CompanyId);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

src/STS.Web/Controllers/DocumentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using STS.Application.Services.Interfaces;
using STS.CrossCutting.Enums;

namespace STS.Web.Controllers
{
    [Authorize]
    public class DocumentsController : BaseController
    {
        private readonly IDocumentService documentService;

        public DocumentsController(IDocumentService documentService)
        {
            this.documentService = documentService;
        }

        public FileContentResult DownloadFile(int id)
        {
            var hasAccess = documentService.HasAccess(UserId, id);
            var isAdmin = User.IsInRole(nameof(UserRole.SuperAdmin));

            if (hasAccess || isAdmin)
            {
                var model = documentService.GetDocument(id);
                return File(model.Data, model.MimeType, model.FileName);
            }

            return null;
        }
    }
}

src/STS.Web/Views/Company/AddDocument.cshtml
@using STS.Web.Controllers
@using STS.Application.Models.Document
@model DocumentUploadViewModel

@{
    ViewBag.Title = "Upload Document";
    Layout = "_CompanyLayout";
}

<div class="container-fluid">
    <div id="upload-document-content"></div>
</div>

@section Scripts{
    <script src="@Url.Content("~/lib/jquery.maskedinput/dist/jquery.maskedinput.min.js")"></script>
    <environment names="Development,Nightly">
        <script src="~/lib/react/react.js"></script>
        <script src="~/lib/react/react-dom.js"></script>
        <script src="@Url.Content("~/js/application/react/constants/constants.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/documentUpload/models.js")"></script>
        <script src="@Url.Content("~/js/application/react/components/confirmation.js")"></script>
        <script src="@Url.Content("~/js/application/react/components/datepicker.js")"></script>
        <script src="@Url.Content("~/js/application/react/components/select.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/documentUpload/categoryItem.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/documentUpload/uploadForm.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/documentUpload/app.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/documentUpload/formDataUtil.js")"></script>
    </environment>
    <environment names="Staging,Production,QA">
        <script src="~/lib/react/react.min.js" asp-append-version="true"></script>
        <script src="~/lib/react/react-dom.min.js" asp-append-version="true"></script>
        <script src="~/js/documentupload.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        ReactDOM.render(React.createElement(DocumentUpload, {
            model: @Json.Serialize(Model),
            saveLink: '@Url.Action("AddDocument")',
            redirectLink: '@Url.Action(nameof(CompanyController.Documents), "Company")'
        }), document.getElementById('upload-document-content'));
    </script>
}

src/STS.Web/Views/Company/Documents.cshtml
@using STS.Application.Filters
@inject IJsonHelper Json
@{
    ViewBag.Title = "Document Progress";
    Layout = "_CompanyLayout";

    var companyId = (int)ViewBag.CompanyId;
    var initialFilter = new Filter
    {
        RowsPerPage = 25,
        SortAscending = true,
        SortColumns = "",
        CurrentPage = 1
    };
}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <h1>@ViewBag.Title</h1>
        </div>
        <div class="col-sm-12 col-md-offset-2 col-md-3">
            <a asp-controller="Company" asp-action="AddDocument" class="btn btn-accent pull-right"><span class="icon icon-plus"></span>Add New Document</a>
        </div>
    </div>
    <div id="documents" data-source-link="@Url.Action("GetDocuments")">
        @await Component.InvokeAsync("CompanyDocumentsGrid", new { filter = initialFilter, companyId })
    </div>
</div>

@section Scripts {
    <script src="~/js/application/uibehaviour/popoverBehaviour.js"></script>
    <script src="~/js/application/grid/ajaxGrid.js"></script>
    <script src="~/js/application/grid/documentsAjaxGrid.js"></script>

    <script>
        $.fn.DocumentsAjaxGrid($('#documents') ,@Json.Serialize(initialFilter));
    </script>
}

src/STS.Web/Views/Company/EditUser.cshtml
@using STS.CrossCutting.Enums
@using STS.Application.Models.User
@model UserEditViewModel

@{
    ViewBag.Title = "Users Management";
    Layout = "_CompanyLayout";
}

<div class="container-fluid">
    <form asp-controller="Company" asp-action="EditUser" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" role="form">
        <div class="edit-form-wr">
            <h1>@(Model.EditMode ? "Edit" : "Create") User</h1>
            <div class="edit-form">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="Id" type="hidden" />
                <div class="edit-form-inner">
                    <div class="title"><span>User Information</span></div>
                    <div class="row edit-form-block">
                        <div class="col-sm-4 form-group">
                            <label asp-for="FirstName"></label>
                            <input asp-for="FirstName" class="form-control" />
                            <span asp-validation-for="FirstName" class="error"></span>
                        </div>
                        <div class="col-sm-4 form-group">
                            <label asp-for="LastName"></label>
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="error"></span>
                        </div>
                        <div class="col-sm-4 form-group">
                            <label asp-for="PhoneNumber"></label>
                            <input asp-for="PhoneNumber" class="form-control phone-input" />
                            <span asp-validation-for="PhoneNumber" class="error"></span>
                        </div>
                    </div>
                    <div class="row edit-form-block">
                        <div class="col-sm-4 form-group">
                            <label asp-for="Email"></label>
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="error"></span>
                        </div>
                        <div class="col-sm-4 form-group">
                            <label asp-for="ConfirmEmail"></label>
                            <input asp-for="ConfirmEmail" class="form-control" />
                            <span asp-validation-for="ConfirmEmail" class="error"></span>
                        </div>
                        <div class="col-sm-4 form-group">
                            <label asp-for="UserName"></label>
                            <input asp-for="UserName" class="form-control" />
                            <span asp-validation-for="UserName" class="error"></span>
                        </div>
                    </div>
                    <div class="row edit-form-block">
                        <div class="col-sm-12 col-md-6">
                            <div class="row">
                                <div class="col-sm-12 col-md-10 nowrap">CHANGE STATUS</div>
                                <div class="col-sm-4 col-md-3 nowrap">
                                    <input id="UserStatus-Active" asp-for="UserStatus" type="radio" value="@UserStatus.Active">
                                    <label for="UserStatus-Active" class="label-radio">Active</label>
                                </div>
                                <div class="col-sm-4 nowrap">
                                    <input id="UserStatus-Deactivated" asp-for="UserStatus" type="radio" value="@UserStatus.Deactivated">
                                    <label for="UserStatus-Deactivated" class="label-radio">Deactivated</label>
                                </div>
                                <div class="col-sm-4 col-md-3 nowrap">
                                    <input id="UserStatus-Locked" asp-for="UserStatus" type="radio" value="@UserStatus.Locked">
                                    <label for="UserStatus-Locked" class="label-radio">Locked</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row edit-form-btns">
                <div class="col-sm-2">
                    <a href="@Url.Action("Users", "Company")" class="btn btn-cancel">Cancel</a>
                </div>
                <div class="col-sm-5">
                    <a href="@Url.Action("ResendEmail", "Account", new {userId = Model.Id}, null)" class="btn btn-default@(Model.EditMode ? "" : " readonly")" @(Model.EditMode ? "" : @" disabled=""disabled""")>
                        Resend Sign Up Email
                    </a>
                </div>
                <div class="col-sm-5">
                    <button class="btn" type="submit">@(Model.EditMode ? "Update" : "Create") User</button>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <script src="~/js/application/inputs/phone.js"></script>
    <script>
        $.fn.PhoneInput($('.phone-input').toArray());
    </script>
}

src/STS.Web/Views/Company/Index.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "_CompanyLayout";
}

<div class="container-fluid">
    <ul class="dashboard-links supplier">
        <li><a asp-controller="Company" asp-action="Users" class="dashboard-links-item user">Manage Users</a></li>
        <li><a asp-controller="Company" asp-action="Sustainability" class="dashboard-links-item accomplishments">Accomplishments & Steps to Next Level</a></li>
        <li><a asp-controller="Company" asp-action="Metrics" class="dashboard-links-item recorders">Environmental Data</a></li>
        <li><a asp-controller="Company" asp-action="Documents" class="dashboard-links-item documents">Document Progress</a></li>
        <li><a asp-controller="Company" asp-action="Survey" class="dashboard-links-item certifications">Survey</a></li>
    </ul>
    <h2> Welcome to the Sustainability Tracking System (STS)!</h2>
</div>

src/STS.Web/Views/Company/Survey.cshtml
@using STS.Application.Models.Company
@using STS.CrossCutting.Enums
@model SurveyViewModel

@{
    ViewBag.Title = "Survey";
    Layout = "_CompanyLayout";
    var index = 0;

    Func<int, AnswerType, string> getIdFor = (number, type) => $"radio-{number}-{type}";
}

<div class="edit-form-wr">
    @if (Model.Questions.Any())
    {
        <h1>Please pass the survey</h1>
    }
    else
    {
        <h1>There are no questions yet</h1>
    }

    @if (Model.Questions.Any())
    {
        <div class="edit-form edit-form-content">
            <form asp-action="Survey">
                @foreach (var item in Model.Questions)
                {
                    @Html.HiddenFor(x => x.Questions[index].QuestionId)
                    <div class="row edit-form-block">
                        <div class="col-sm-9">
                            <h2>@item.Text</h2>
                        </div>
                        <div class="col-sm-1 nowrap">
                            @Html.RadioButtonFor(x => x.Questions[index].Answer, AnswerType.Yes, new {id = getIdFor(index, AnswerType.Yes)})
                            @Html.Label(getIdFor(index, AnswerType.Yes), "Yes", new {@class = "label-radio"})
                        </div>
                        <div class="col-sm-1 nowrap">
                            @Html.RadioButtonFor(x => x.Questions[index].Answer, AnswerType.No, new {id = getIdFor(index, AnswerType.No)})
                            @Html.Label(getIdFor(index, AnswerType.No), "No", new {@class = "label-radio"})
                        </div>
                        <div class="col-sm-1 nowrap">
                            @Html.RadioButtonFor(x => x.Questions[index].Answer, AnswerType.None, new {id = getIdFor(index, AnswerType.None)})
                            @Html.Label(getIdFor(index, AnswerType.None), "Not sure", new {@class = "label-radio"})
                        </div>
                    </div>
                    <hr/>
                    index++;
                }
                <div class="row edit-form-btns">
                    <div class="col-sm-3 col-sm-offset-5">
                        <a href="@Url.Action("Index", "Company")" class="btn btn-cancel">Cancel</a>
                    </div>
                    <div class="col-sm-4">
                        <button class="btn" type="submit">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    }
</div>

src/STS.Web/Views/Company/Sustainability.cshtml
@using System.Threading.Tasks
@using STS.Application.Models.Sustainability
@model SustainabilityPageViewModel
@addTagHelper STS.Web.TagHelpers.CategoryTabTagHelper, STS.Web

@{
    Layout = "_CompanyLayout";
    ViewBag.Title = "Sustainability Levels";

    ViewBag.PageSettings = new SustainabilityPageSettingsViewModel
    {
        HeaderTitle = "Accomplishments & Steps to Next Level",
        Controller = "Company",
        Action = "Sustainability"
    };
}

@Html.Partial("SupplierSustainability/SustainabilityPage", Model)

src/STS.Web/Views/Company/Users.cshtml
@using STS.Application.Filters
@inject IJsonHelper Json
@{
    ViewBag.Title = "Users Management";
    Layout = "_CompanyLayout";

    var companyId = (int)ViewBag.CompanyId;
    var initialFilter = new Filter
    {
        RowsPerPage = 25,
        SortAscending = true,
        SortColumns = "",
        CurrentPage = 1
    };
}

<div class="container-fluid">
    <div id="users" data-source-link="@Url.Action("GetUsers")">
        @await Component.InvokeAsync("CompanyUsersGrid", new { filter = initialFilter, companyId })
    </div>
</div>

@section Scripts {
    <script src="~/js/application/grid/ajaxGrid.js"></script>
    <script>
        $.fn.AjaxGrid($('#users') ,@Json.Serialize(initialFilter));
    </script>
}