src/STS.Web/Components/AdminCompaniesGridViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using STS.Application.Filters;
using STS.Application.Services.Interfaces;

namespace STS.Web.Components
{
    public class AdminCompaniesGridViewComponent : ViewComponent
    {
        private readonly IAdminService adminService;

        public AdminCompaniesGridViewComponent(IAdminService adminService)
        {
            this.adminService = adminService;
        }

        public IViewComponentResult Invoke(IFilter filter)
        {
            var filterResult = adminService.FilterCompanies(filter);
            return View(filterResult);
        }
    }
}

src/STS.Web/Components/AdminQuestionsGridViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using STS.Application.Filters;
using STS.Application.Services.Interfaces;

namespace STS.Web.Components
{
    public class AdminQuestionsGridViewComponent : ViewComponent
    {
        private readonly IAdminService adminService;

        public AdminQuestionsGridViewComponent(IAdminService adminService)
        {
            this.adminService = adminService;
        }

        public IViewComponentResult Invoke(IFilter filter)
        {
            var filterResult = adminService.FilterQuestions(filter);
            return View(filterResult);
        }
    }
}

src/STS.Web/Components/AdminUsersGridViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using STS.Application.Filters;
using STS.Application.Services.Interfaces;

namespace STS.Web.Components
{
    public class AdminUsersGridViewComponent : ViewComponent
    {
        private readonly IAdminService adminService;

        public AdminUsersGridViewComponent(IAdminService adminService)
        {
            this.adminService = adminService;
        }

        public IViewComponentResult Invoke(Filter filter)
        {
            var filterResult = adminService.FilterUsers(filter);
            return View(filterResult);
        }
    }
}

src/STS.Web/Views/Admin/Companies.cshtml
@using System.Threading.Tasks
@using STS.Application.Filters
@inject IJsonHelper Json

@{
    ViewBag.Title = "Manage Companies";
    var companyId = (int)ViewBag.CompanyId;
    Layout = "_AdminLayout";

    var initialFilter = new Filter
    {
        RowsPerPage = 25,
        SortAscending = true,
        SortColumns = "",
        CurrentPage = 1
    };
}

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12 col-sm-8">
            <h1>@ViewBag.Title</h1>
        </div>
        <div class="col-xs-12 col-sm-4">
            <a asp-controller="Admin" asp-action="EditCompany" class="btn btn-accent pull-right"><span class="icon icon-plus"></span>Add New Company</a>
        </div>
    </div>
    <div id="companies" data-source-link="@Url.Action("GetCompanies")">
        @await Component.InvokeAsync("AdminCompaniesGrid", new { filter = initialFilter, companyId })
    </div>
</div>

@section Scripts {
    <script src="~/js/application/grid/ajaxGrid.js"></script>
    <script>
        $.fn.AjaxGrid($('#companies') ,@Json.Serialize(initialFilter));
    </script>
}

src/STS.Web/Views/Admin/EditCompany.cshtml
@using System.Threading.Tasks
@using STS.Application.Models.Admin
@model  CompanyEditViewModel

@{
    ViewBag.Title = $"{(ViewBag.EditMode != null && ViewBag.EditMode == true ? "Edit" : "Create")} Lead Company";
    Layout = "_AdminLayout";
}

@Html.ValidationSummary()

<form id="lead-edit-form" asp-controller="Admin" asp-action="EditCompany" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" role="form" enctype="multipart/form-data">
    <input asp-for="EditMode" type="hidden" />
    <div class="edit-form-wr">
        <h1>@($"{ViewBag.Title} Account")</h1>
        <div class="edit-form">
            <div class="edit-form-inner">
                <div class="title"><span>Company Information</span></div>
                @Html.EditorFor(x => x.Company)
                @if (!Model.EditMode)
                {
                    <div class="title"><span>Company Administrator</span></div>
                    @Html.EditorFor(x => x.Administrator)
                }
            </div>
        </div>
        <div class="row edit-form-btns">
            <div class="col-sm-6">
                <a href="@Url.Action("Companies", "Admin")" class="btn btn-cancel">Cancel</a>
            </div>
            <div class="col-sm-6">
                <button id="save" type="submit" class="btn">
                    @($"{(Model.EditMode ? "Update" : "Create")} Lead Company")
                </button>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    <script src="~/js/application/supplier/companyEditor.js"></script>
    <script src="~/js/application/inputs/phone.js"></script>
    <script src="~/js/application/inputs/numeric.js"></script>
    <script src="~/js/application/inputs/date.js"></script>
    <script src="~/js/application/inputs/currency.js"></script>
    <script src="~/js/application/inputs/zipCode.js"></script>
    <script src="~/js/application/supplier/supplierEditor.js"></script>
    <script>
        $.fn.CompanyEditorForm($('#select-state').toArray(), $('.lazy-password').toArray());
        $.fn.PhoneInput($('.phone-input').toArray());
        $.fn.SupplierEditorForm($('#AdminIsPrimaryContact'));
        $.fn.CurrencyInput("#AnnualProcurementBudget");
        $.fn.ZipCodeInput("#Zip");
        $(document).ready(function () {
            $.fn.DateInput('#SubscriptionExpirationDate');
            setTimeout(function () {
                $(".code-search").codeInput();
            }, 10);
        });
        function confirm(editMode) {
            let message = "Are you sure you want to ";
            message += editMode ? "save this data?" : "create " + $('#LeadCompany_Name').val() + " as a new lead company?";
            $.fn.confirmationDialog(null, function () { $('#lead-edit-form').submit(); return false; }, message);
        }
    </script>
}

src/STS.Web/Views/Admin/EditQuestion.cshtml
@using STS.Application.Models.Admin
@model QuestionEditViewModel

@{
    ViewBag.Title = "Questions Management";
    Layout = "_AdminLayout";
}

<div class="container-fluid">
    <form asp-controller="Admin" asp-action="EditQuestion" method="post" role="form">
        <div class="edit-form-wr">
            <h1>@(Model.EditMode ? "Edit" : "Create") Question</h1>
            <div class="edit-form">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="Id" type="hidden" />
                <input asp-for="EditMode" type="hidden" />
                <div class="edit-form-inner">
                    <div class="title"><span>Question Information</span></div>
                    <div class="row edit-form-block">
                        <div class="col-sm-12 form-group">
                            <label asp-for="Text"></label>
                            <input asp-for="Text" class="form-control" />
                            <span asp-validation-for="Text" class="error"></span>
                        </div>
                    </div>
                    <div class="row edit-form-block">
                        <div class="col-sm-4 form-group">
                            <label asp-for="YesAnswerPoints"></label>
                            <input asp-for="YesAnswerPoints" class="form-control" />
                            <span asp-validation-for="YesAnswerPoints" class="error"></span>
                        </div>
                        <div class="col-sm-4 form-group">
                            <label asp-for="NoAnswerPoints"></label>
                            <input asp-for="NoAnswerPoints" class="form-control phone-input" />
                            <span asp-validation-for="NoAnswerPoints" class="error"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row edit-form-btns">
                <div class="col-sm-6">
                    <a href="@Url.Action("Questions", "Admin")" class="btn btn-cancel">Cancel</a>
                </div>
                <div class="col-sm-6">
                    <button class="btn" type="submit">@(Model.EditMode ? "Update" : "Create") Question</button>
                </div>
            </div>
        </div>
    </form>
</div>

src/STS.Web/Views/Admin/EditUser.cshtml
@using STS.CrossCutting.Enums
@using STS.Application.Models.User
@model UserEditViewModel

@{
    ViewBag.Title = "Users Management";
    var editMode = Model.Id > 0;
    Layout = "_AdminLayout";
}

<div class="container-fluid">
    <form asp-controller="Admin" asp-action="EditUser" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" role="form">
        <div class="edit-form-wr">
            <h1>@(editMode ? "Edit" : "Create") User</h1>
            <div class="edit-form">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="Id" type="hidden" />
                <div class="edit-form-inner">
                    <div class="title"><span>User Information</span></div>
                    <div class="row edit-form-block">
                        <div class="col-sm-4 form-group">
                            <label asp-for="FirstName"></label>
                            <input asp-for="FirstName" class="form-control" />
                            <span asp-validation-for="FirstName" class="error"></span>
                        </div>
                        <div class="col-sm-4 form-group">
                            <label asp-for="LastName"></label>
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="error"></span>
                        </div>
                        <div class="col-sm-4 form-group">
                            <label asp-for="PhoneNumber"></label>
                            <input asp-for="PhoneNumber" class="form-control phone-input" />
                            <span asp-validation-for="PhoneNumber" class="error"></span>
                        </div>
                    </div>
                    <div class="row edit-form-block">
                        <div class="col-sm-4 form-group">
                            <label asp-for="Email"></label>
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="error"></span>
                        </div>
                        <div class="col-sm-4 form-group">
                            <label asp-for="ConfirmEmail"></label>
                            <input asp-for="ConfirmEmail" class="form-control" />
                            <span asp-validation-for="ConfirmEmail" class="error"></span>
                        </div>
                        <div class="col-sm-4 form-group">
                            <label asp-for="UserName"></label>
                            <input asp-for="UserName" class="form-control" />
                            <span asp-validation-for="UserName" class="error"></span>
                        </div>
                    </div>
                    <div class="row edit-form-block">
                        <div class="col-sm-12 col-md-6">
                            <div class="row">
                                <div class="col-sm-12 col-md-10 nowrap">CHANGE STATUS</div>
                                <div class="col-sm-4 col-md-3 nowrap">
                                    <input id="UserStatus-Active" asp-for="UserStatus" type="radio" value="@UserStatus.Active">
                                    <label for="UserStatus-Active" class="label-radio">Active</label>
                                </div>
                                <div class="col-sm-4 nowrap">
                                    <input id="UserStatus-Deactivated" asp-for="UserStatus" type="radio" value="@UserStatus.Deactivated">
                                    <label for="UserStatus-Deactivated" class="label-radio">Deactivated</label>
                                </div>
                                <div class="col-sm-4 col-md-3 nowrap">
                                    <input id="UserStatus-Locked" asp-for="UserStatus" type="radio" value="@UserStatus.Locked">
                                    <label for="UserStatus-Locked" class="label-radio">Locked</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row edit-form-btns">
                <div class="col-sm-6">
                    <a href="@Url.Action("Users", "Admin")" class="btn btn-cancel">Cancel</a>
                </div>
                <div class="col-sm-6">
                    <button class="btn" type="submit">@(editMode ? "Update" : "Create") User</button>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <script src="~/js/application/inputs/phone.js"></script>
    <script>
        $.fn.PhoneInput($('.phone-input').toArray());
    </script>
}

src/STS.Web/Views/Admin/Index.cshtml
@{
    Layout = "_AdminLayout";
    ViewBag.Title = "Dashboard";
}

<div class="container-fluid">
    <h2>Welcome to the Sustainability Tracking System (STS)!</h2>
    <br>
    <ul class="dashboard-links">
        <li><a asp-controller="Admin" asp-action="Users" class="dashboard-links-item users">Manage Users</a></li>
        <li><a asp-controller="Admin" asp-action="Companies" class="dashboard-links-item suppliers">Manage Companies</a></li>
        <li><a asp-controller="Admin" asp-action="Reports" class="dashboard-links-item reporting">Reporting</a></li>
        <li><a asp-controller="Admin" asp-action="Sustainability" class="dashboard-links-item sustainability">Company Sustainability</a></li>
        <li><a asp-controller="Admin" asp-action="Rules" class="dashboard-links-item levels">Manage Sustainability Levels</a></li>
        <li><a asp-controller="Admin" asp-action="Questions" class="dashboard-links-item certifications">Manage Questions</a></li>
    </ul>
</div>

src/STS.Web/Views/Admin/Questions.cshtml
@using System.Threading.Tasks
@using STS.Application.Filters
@inject IJsonHelper Json

@{
    ViewBag.Title = "Manage Questions";
    Layout = "_AdminLayout";

    var initialFilter = new Filter
    {
        RowsPerPage = 25,
        SortAscending = true,
        SortColumns = "",
        CurrentPage = 1
    };
}

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12 col-sm-8">
            <h1>@ViewBag.Title</h1>
        </div>
        <div class="col-xs-12 col-sm-4">
            <a asp-controller="Admin" asp-action="EditQuestion" class="btn btn-accent pull-right"><span class="icon icon-plus"></span>Add New Question</a>
        </div>
    </div>
    <div id="questions" data-source-link="@Url.Action("GetQuestions")">
        @await Component.InvokeAsync("AdminQuestionsGrid", new { filter = initialFilter })
    </div>
</div>

@section Scripts {
    <script src="~/js/application/grid/ajaxGrid.js"></script>
    <script>
        $.fn.AjaxGrid($('#questions') ,@Json.Serialize(initialFilter));
    </script>
}

src/STS.Web/Views/Admin/Reports.cshtml
@using System.Threading.Tasks
@using STS.Application.Models.Report
@model ReportsViewModel

@{
    ViewBag.Title = "Reporting";
    Layout = "_AdminLayout";
}

<form asp-controller="Admin" asp-action="Reports" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" role="form">
    <div class="edit-form-wr">
        <h1>Reporting</h1>
        <div class="edit-form">
            <div class="edit-form-inner">
                <div class="title"><span>Select type</span></div>
                <div class="row edit-form-block vcenter">
                    <div class="col-xs-12 col-md-8">
                        <div class="row">
                            <div class="col-xs-12 form-group">
                                <label asp-for="ReportType"></label>
                                <select asp-for="ReportType" asp-items="@Model.Reports" class="chosen-select form-control" id="select-report"></select>
                            </div>
                        </div>
                        <div class="row" id="dates-block" style="display: none">
                            <div class="col-xs-6 form-group">
                                <label asp-for="StartDate"></label>
                                <input asp-for="StartDate" type="text" class="form-control report-date">
                                <span asp-validation-for="StartDate" class="error"></span>
                            </div>
                            <div class="col-xs-6 form-group">
                                <label asp-for="EndDate"></label>
                                <input asp-for="EndDate" type="text" class="form-control report-date">
                                <span asp-validation-for="EndDate" class="error"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-4 form-group text-center">
                        <button id="generation" type="button" class="btn">Generate</button>
                    </div>
                </div>
                <div class="title"><span>Report</span></div>
                <div class="row edit-form-block">
                    <div id="chart-container">
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    <script src="~/js/application/inputs/date.js"></script>
    <script src="~/js/application/report/chartContainer.js"></script>
    <script src="~/js/application/report/generation.js"></script>
    <script src="~/js/application/report/datesBlock.js"></script>
    <script src="~/js/application/report/reportTypes.js"></script>
    <script src="~/js/application/report/reports.js"></script>
    <script src="~/js/application/report/charts/supplierDistributionBySustainabilityLevelSpendAdjusted.js"></script>
    <script src="~/js/application/report/charts/SupplierDistributionBySustainabilityLevelTotal.js"></script>
    <script src="~/js/application/report/charts/supplierScope1Scope2Emissions.js"></script>
    <script src="~/js/application/report/charts/monthlySupplierParticipationTrendSpendAdjusted.js"></script>
    <script>
        $(function () {
            var options = {
                minViewMode: "months",
                todayHighlight: true,
                maxViewMode: "years",
                orientation: "bottom right"
            };
            $.fn.DateInput("#StartDate", options);
            $.fn.DateInput("#EndDate", options);
        });
        $.fn.Generation($('#generation'), $("#chart-container"));
        $.fn.DatesBlock($('#select-report'), $('#dates-block'));
    </script>
}

src/STS.Web/Views/Admin/Rules.cshtml
@using System.Threading.Tasks
@using STS.Application.Models.Category
@model CategoriesViewModel
@{
    ViewBag.Title = "Manage Sustainability Levels";
    Layout = "_AdminLayout";
}

<div id="sustainability-categories-content"></div>

@section Scripts{
    <environment names="Development,Nightly">
        <script src="~/lib/react/react.js"></script>
        <script src="~/lib/react/react-dom.js"></script>
        <script src="@Url.Content("~/js/application/react/components/confirmation.js")"></script>
        <script src="@Url.Content("~/js/application/react/components/inputGroup.js")"></script>
        <script src="@Url.Content("~/js/application/react/components/datepicker.js")"></script>
        <script src="@Url.Content("~/js/application/react/components/select.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/sustanabilityApp/models.js")"></script>
        <script src="@Url.Content("~/js/application/react/stores/eventEmitter.js")"></script>
        <script src="@Url.Content("~/js/application/react/stores/baseStore.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/sustanabilityApp/store.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/sustanabilityApp/app.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/sustanabilityApp/page.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/sustanabilityApp/tab.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/sustanabilityApp/tabs.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/sustanabilityApp/items/document.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/sustanabilityApp/items/survey.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/sustanabilityApp/items/metric.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/sustanabilityApp/containers/todoContainer.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/sustanabilityApp/containers/documentContainer.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/sustanabilityApp/containers/surveyContainer.js")"></script>
        <script src="@Url.Content("~/js/application/react/applications/sustanabilityApp/containers/metricContainer.js")"></script>
    </environment>
    <environment names="Staging,Production,QA">
        <script src="~/lib/react/react.min.js" asp-append-version="true"></script>
        <script src="~/lib/react/react-dom.min.js" asp-append-version="true"></script>
        <script src="~/js/sustanability.min.js" asp-append-version="true"></script>
    </environment>
    

    <script>
        ReactDOM.render(
            React.createElement(Sustainability.SustanabilityApplication,
            {
                model: @Json.Serialize(Model),
                saveLink: '@Url.Action("Rules")',
                redirectLink: '@Url.Action("Index", "Home")'
            }),
            document.getElementById('sustainability-categories-content'));
    </script>
}

src/STS.Web/Views/Admin/Users.cshtml
@using STS.Application.Filters
@inject IJsonHelper Json

@{
    Layout = "_AdminLayout";
    ViewBag.Title = "Manage Users";

    var initialFilter = new Filter
    {
        RowsPerPage = 25,
        SortAscending = true,
        SortColumns = "",
        CurrentPage = 1
    };
}

<div class="container-fluid">
    <div id="users" data-source-link="@Url.Action("GetUsers", "Admin")">
        @await Component.InvokeAsync("AdminUsersGrid", new { filter = initialFilter })
    </div>
</div>

@section Scripts {
    <script src="~/js/application/grid/ajaxGrid.js"></script>
    <script>
        $.fn.AjaxGrid($('#users') ,@Json.Serialize(initialFilter));
    </script>
}