src/STS.Web/Controllers/DocumentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using STS.Application.Services.Interfaces;
using STS.CrossCutting.Enums;

namespace STS.Web.Controllers
{
    [Authorize]
    public class DocumentsController : BaseController
    {
        private readonly IDocumentService documentService;

        public DocumentsController(IDocumentService documentService)
        {
            this.documentService = documentService;
        }

        public FileContentResult DownloadFile(int id)
        {
            var hasAccess = documentService.HasAccess(UserId, id);
            var isAdmin = User.IsInRole(nameof(UserRole.SuperAdmin));

            if (hasAccess || isAdmin)
            {
                var model = documentService.GetDocument(id);
                return File(model.Data, model.MimeType, model.FileName);
            }

            return null;
        }
    }
}

src/STS.Web/Views/Shared/SupplierSustainability/DocumentAchievementsView.cshtml
@using System.Threading.Tasks
@using STS.Application.Models.Sustainability.AchievementItems
@using STS.Application.Models.Sustainability.AchievementItems.SuitableItems
@using STS.CrossCutting.Utils
@model IList<BaseAchievementItemViewModel>

@{
    var items = Model.Cast<DocumentAchievementItemViewModel>();
}

@foreach (var achievementModel in items)
{
    <div class="c-levels-description-item">
        <div class="c-levels-description-text">
            @if (achievementModel.Achieved)
            {
                <div class="icon icon-level-check">
                    @foreach (var document in achievementModel.Documents)
                    {
                        <p>
                            The document, <a href="@Url.Action("DownloadFile", "Documents", new {id = document.Id})">"@document.Name"</a>
                           @achievementModel.DocumentTypeName will be used to support your company's sustainability level in the STS until @document.ExpireDate.ToString(@"MM\/dd\/yy").
                            This date is @achievementModel.ConsiderationTimeInMonths months @(((Enum) achievementModel.ConsiderationTime).DisplayName().ToLowerInvariant()).
                        </p>
                    }
                </div>
            }
            else
            {
                <p class="icon icon-level-clock">
                    <b>
                        @(achievementModel.Documents?.Count > 0
                              ? $"You've uploaded {achievementModel.Documents.Count}(s) {achievementModel.DocumentTypeName}. Please upload {achievementModel.Quantity - (achievementModel.Documents.Count)} additional {achievementModel.DocumentTypeName}(s)."
                              : $"Upload {achievementModel.Quantity} {achievementModel.DocumentTypeName}(s)")
                    </b>
                </p>
                <p>
                    @achievementModel.DocumentTypeName will be used to support your company's sustainability level.
                    @(achievementModel.Quantity > 1 ? "They" : "It") will support your sustainability level for @achievementModel.ConsiderationTimeInMonths months @(((Enum) achievementModel.ConsiderationTime).DisplayName().ToLowerInvariant()).
                </p>

                foreach (var document in achievementModel.Documents ?? new List<DocumentItemViewModel>())
                {
                    <p>
                        <a href="@Url.Action("DownloadFile", "Documents", new {id = document.Id})">@achievementModel.DocumentTypeName</a> will be used to support your company's sustainability level in the STS until @document.ExpireDate.ToString(@"MM\/dd\/yy").
                        It will support your sustainability level for @achievementModel.ConsiderationTimeInMonths months @(((Enum)achievementModel.ConsiderationTime).DisplayName().ToLowerInvariant()).
                    </p>
                }
            }
        </div>
    </div>
}

src/STS.Web/Views/Shared/SupplierSustainability/MetricAchievementsView.cshtml
@using STS.Application.Models.Sustainability.AchievementItems
@using STS.CrossCutting.Enums
@using STS.CrossCutting.Utils
@model IList<BaseAchievementItemViewModel>

@{
    var items = Model.Cast<MetricAchievementItemViewModel>();
}

@foreach (var item in items)
{
    var beavior = (item.Increase ? "increase" : "reduction");
    var timeConsidirationToUserString = item.ConsiderationTime == MetricConsideration.FromEnterDate
        ? "from the date when you submitted this information to the STS"
        : "from the end of the time period associated with this accomplishment";
    var trendString = ((Enum) item.MetricTrend).DisplayName();
    var trendStringLower = char.ToLowerInvariant(trendString[0]) + trendString.Substring(1);
    var trendHeading = $"{(item.Increase ? "Increase" : "Decrease")} {trendStringLower} by {item.ThresholdByRule}%";
    <div class="c-levels-description-item">
        <div class="c-levels-description-text">
            @if (item.Achieved)
            {
                <p class="icon icon-level-check">
                    @trendHeading
                </p>
                <p class="icon-level-check">
                    Your @trendStringLower @(item.Increase ? "increase" : "decrease") by @($"{Math.Abs(item.ThresholdCurrent):0}")%,
                    which satisfied the requirement of a @(item.ThresholdByRule)% @beavior in comparison to the base year.
                    Your accomplishment of @(((Enum)item.MetricTrend).DisplayName()) @beavior will be used to support your company's sustainability level in the STS
                    until @item.ExpireDate.ToString(@"MM\/dd\/yy"). This date is @item.ConsiderationTimeInMonths months @timeConsidirationToUserString.
                </p>
            }
            else
            {
                <p class="icon icon-level-clock">
                    <b>
                       @trendHeading
                    </b>
                </p>
                <p>
                    @(((Enum)item.MetricTrend).DisplayName()) should be @(item.Increase ? "increase" : "decrease") by @(item.ThresholdByRule)% in comparison to base year.
                </p>
                <p>
                    Your accomplishment of @trendStringLower will be used to support your company's sustainability level
                    for @item.ConsiderationTimeInMonths months @timeConsidirationToUserString.
                </p>
            }
        </div>
    </div>
}

src/STS.Web/Views/Shared/SupplierSustainability/SurveyAchievementsView.cshtml
@using STS.Application.Models.Sustainability.AchievementItems
@model IList<BaseAchievementItemViewModel>

@{
    var achievementCollection = Model.Cast<SurveyAchievementItemViewModel>();
}

@foreach (var achievementModel in achievementCollection)
{
    <div class="c-levels-description-item">
        <div class="c-levels-description-text">
            @if (achievementModel.Achieved)
            {
                <p class="icon icon-level-check">
                    You've completed survey with @achievementModel.RequiredScores point(s).
                </p>
            }
            else
            {
                <p class="icon icon-level-clock">
                    <b>Required survey points: @achievementModel.RequiredScores</b>
                </p>
            }
        </div>
    </div>
}

src/STS.Web/Views/Shared/SupplierSustainability/SustainabilityPage.cshtml
@using System.Threading.Tasks
@using STS.Application.Models.Sustainability
@using STS.CrossCutting.Enums
@using SustainabilityLevel = STS.Application.Models.Sustainability.SustainabilityLevel
@model SustainabilityPageViewModel
@addTagHelper STS.Web.TagHelpers.CategoryTabTagHelper, STS.Web

@{
    Layout = null;

    var pageSettings = (SustainabilityPageSettingsViewModel)ViewBag.PageSettings;

    var targetController = pageSettings.Controller;
    var targetAction = pageSettings.Action;

    var achievements = Model.TargetCategoryModel.Achievements;
    var documentAchievement = achievements.First(x => x.AchievementType == TodoType.DocumentTodo);
    var surveyAchievement = achievements.First(x => x.AchievementType == TodoType.SurveyTodo);
    var metricAchievement = achievements.First(x => x.AchievementType == TodoType.MetricTodo);

    var shouldDisplayButton =
        Model.Categories.Max(x => x.OrderWeight) > Model.TargetCategoryWeight ||
        Model.CurrentCategoryWeight < Model.TargetCategoryWeight;

    var currentCategoryLink = Url.Action(targetAction, targetController, new { categoryId = Model.CurrentCategoryId });

    var nextCategoryLink = Url.Action(targetAction, targetController, new { categoryId = Model.CurrentCategoryId + 1 });

    var titlePanelClass = Model.TargetCategoryLevel == SustainabilityLevel.Current
        ? "current"
        : "";

    var hasItems = documentAchievement.AchievementItems.Any() || surveyAchievement.AchievementItems.Any() || metricAchievement.AchievementItems.Any();
}

<div class="edit-form-wr">
    <h1>@pageSettings.HeaderTitle</h1>

    <div class="edit-form edit-form-content">
        <div class="c-levels-wr">
            <div class="c-levels">
                @if (Model.CurrentCategoryId == 0)
                {
                    <a href="@currentCategoryLink" class="c-levels-item c-levels-item-red active">
                        <b class="c-levels-item-check"><span></span></b>
                        <span>No response</span>
                        (Current)
                    </a>
                }
                else
                {
                    <a href="javascript:void(0)" class="c-levels-item">
                        <b class="c-levels-item-check"><span></span></b>
                        <span>No response</span>
                        (Achieved)
                    </a>
                }

                @foreach (var item in Model.Categories)
                {
                    <category-tab controller="@targetController" action="@targetAction" item="@item" category-id="@Model.TargetCategoryId">
                    </category-tab>
                }
            </div>
        </div>

        <div class="panel-collapse">
            <div class="title @titlePanelClass">
                @if (Model.TargetCategoryLevel == SustainabilityLevel.Current)
                {
                    <span>Current Sustainability Level: @Model.TargetCategoryName</span>
                }
                else if (Model.TargetCategoryLevel == SustainabilityLevel.Next)
                {
                    <span>Next Sustainability Level: @Model.TargetCategoryName</span>
                }
                else if (Model.TargetCategoryLevel == SustainabilityLevel.Future)
                {
                    <span>Future Sustainability Level: @Model.TargetCategoryName</span>
                }

                @if (Model.TargetCategoryLevel == SustainabilityLevel.Current && shouldDisplayButton)
                {
                    <a href="@nextCategoryLink" class="btn btn-cancel next">Steps to Next Level</a>
                }
                else if (Model.TargetCategoryLevel != SustainabilityLevel.Current && shouldDisplayButton)
                {
                    <a href="@currentCategoryLink" class="btn btn-cancel back">Back to Current Level</a>
                }
            </div>

            @if ((Model.TargetCategoryLevel == SustainabilityLevel.Future || Model.TargetCategoryLevel == SustainabilityLevel.Next) && hasItems)
            {
                <p class="subtitle">Requirements to Complete this Sustainability Level</p>
                <p style="padding: 0 0 0 58px; margin-top: -10px">NOTE: The rules for all preceding sustainability levels must be satisfied in addition to the requirements for this sustainability level, which are described below.</p>
            }

            <div class="panel-body c-levels-description">
                <div class="panel-group">
                    @if (Model.CurrentCategoryId == 0 && Model.TargetCategoryId == 0)
                    {
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    No Activity
                                </h4>
                            </div>
                        </div>
                    }

                    @if (hasItems)
                    {
                        if (documentAchievement.AchievementItems.Any())
                        {
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <a data-toggle="collapse" href="#achievements">Achievements</a>
                                    </h4>
                                </div>
                                <div id="achievements" class="panel-collapse collapse in">
                                    <div class="panel-body c-level-description">
                                        @Html.Partial("SupplierSustainability/DocumentAchievementsView", documentAchievement.AchievementItems)
                                    </div>
                                </div>
                            </div>
                        }

                        if (surveyAchievement.AchievementItems.Any())
                        {
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <a data-toggle="collapse" href="#surveys">Survey Status</a>
                                    </h4>
                                </div>
                                <div id="surveys" class="panel-collapse collapse in">
                                    <div class="panel-body c-level-description">
                                        @Html.Partial("SupplierSustainability/SurveyAchievementsView", surveyAchievement.AchievementItems)
                                    </div>
                                </div>
                            </div>
                        }

                        if (metricAchievement.AchievementItems.Any())
                        {
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <a data-toggle="collapse" href="#metrics">Metric Trends</a>
                                    </h4>
                                </div>
                                <div id="metrics" class="panel-collapse collapse in">
                                    <div class="panel-body c-level-description">
                                        @Html.Partial("SupplierSustainability/MetricAchievementsView", metricAchievement.AchievementItems)
                                    </div>
                                </div>
                            </div>
                        }
                    }
                    else
                    {
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    There are no rules configured for this level.
                                </h4>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>